version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - appnetwork

  backend:
    environment:
      - NODE_ENV=test
    build:
      context: ./backend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
